# Generated by Django 5.0 on 2024-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_rollnumber_employee_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
